Config({
    "network-name": "هواوي" ,
    "service-number": "772877987",
    "login-type": "user",
    "news-line": "شبكة هواوي اللاسلكية الشبكة الأقوى و الأسرع و الأختيار الأفضل",
    "news-line2": "",
    "input-type": "text",
    "speed-trychange": 3 ,//عدد مرات سماح التغيير
    "speed-trychange-timeout": 3 ,// مدة فترة  حضر التغيير بالدقائق
    "input-autocomplete": "on",
    "input-rm-white-spaces": 1,
    "input-to-lower": 1,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "input-to-text-type-when": 0,
    "enable-hot-cookie": 0,
    "enable-hot-blocker": 1,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 2,
    "try-count": 5,
    "warn-when": 3,
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات",
    "price-button": true,
    "sell-point-button": true,
    "app-store-status-button": false,
    "show-date-field": false,
    "loan-button": true,
    "redirect-to-esterahah": "http://199.168.2.100:8090/ng",// orWithProtocol: ex, https://google.com leave it blank if dont need esterahah button
    "redirect-to-mobasher": "",// orWithProtocol: ex, https://google.com leave it blank if dont need mobasher button
    "app-store-base-url": "",// orWithProtocol: ex, http://192.168.10.10/app/ // leave it blank if locally
    "profiles": [
        {
            "price": "100 ريال",
            "time": "4 ساعات",
            "transfer": "300 ميجا",
            "validity": "3 ايام",
        },
        {
            "price": "200 ريال",
            "time": "8 ساعات",
            "transfer": "600 ميجا",
            "validity": "6 ايام",
        },
        {
            "price": "300 ريال",
            "time": "12 ساعة",
            "transfer": "800 ميجا",
            "validity": "9 ايام",
        },
        {
            "price": "500 ريال",
            "time": "20 ساعة",
            "transfer": "1400 ميجا",
            "validity": "20 يوم",
        },
        {
            "price": "500 ريال",
            "time": "باقة واتس  ",
            "transfer": "1 جيجا",
            "validity": "30 يوم",
        }, {
            "price": "700 ريال",
            "time": " أسبوعي",
            "transfer": "2 جيجا",
            "validity": "7 ايام",
        },
         {
            "price": "1300 ريال",
            "time": " نصف شهر",
            "transfer": "4 جيجا",
            "validity": "15 يوم",
        },
         {
            "price": "2500 ريال",
            "time": " شهر",
            "transfer": "7 جيجا",
            "validity": "30يوم ",
        }
    ],
    "sell-points": [
        {"name": "--حارة السعيد--"},
        {"name": "بقالة منيف الشرعبي"},
        {"name": "بقالة عدنان الشرعبي"},
        {"name": "بقالة باب الحارة"},
        {"name": "بقالة ذي يزن"},
        {"name": "بقالة سامي"},
        {"name": "بقالة عبده سعيد"},
        {"name": "بقالة العوني"},
        {"name": "--حارة القرية--"},
        {"name": "بقالة الخضمي"},
        {"name": "بقالة جبريل"},
        {"name": "بقالة نعيم السلطان"},
        {"name": "بقالة هاني"},
        {"name": "بقالة فؤاد الشرعبي"},
        {"name": "بقالة الحجة"},
        {"name": "بقالة القعقاع"},
        {"name": "بقالة فاضل"},
        {"name": "--حارة عمار--"},
        {"name": "بقالة الجباري"},
        {"name": "بقالة رافت الكابوس"},
        {"name": "بقالة عبدالعالم"},
        {"name": "--حارة المعامرة--"},
        {"name": "بقالة سليم الشرعبي"},
        {"name": "كشك الوحدة"},
        {"name": "بقالة حمود القرن"},
        {"name": "ايسكريم رشاد"},
        {"name": "بقالة وحيد"},
        {"name": "بقالة ابراهيم"},
        {"name": "مكتبة الطيار"},
        {"name": "--حارة المعهد العالي*كلية المجتمع*--"},
        {"name": "مكتبة المحترف"},
        {"name": "مكتبة دبي"}
      ]
})
